### ISSUE TITLE
As a developer I have to setup my project, so that I can continue developing features

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#24]
As a developer I have to setup my project, so that I can continue developing features

**Acceptance Criteria**

- [x] Project runs locally without any issues
- [x] All the dependencies are managed properly

**Tasks**
- [x] Configure the project to run locally
- [x] Manage dependencies
