### ISSUE TITLE
As a user I want to view my profile detials, so that I can verify the details are up to date

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#47]
EPIC: #39 

As a user I want to view my profile detials, so that I can verify the details are up to date

** Acceptance Criteria**

- [x] - Profile page easily accessible for the signed in user
- [x] - Profile must be retrieved through a REST API service
- [x] - Profile page must be easily accessble from the navbar

**Tasks**

- [x] - Design and implement the profile page
- [x] - Implement image upload functionality using cloudinary as the content server
- [x] - Profile view must load the editable details in to editable form components
- [x] - Add unit tests
