### ISSUE TITLE
As a user I want to view other user profiles, so that I can get to know the other users

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#48]
EPIC: #39 

As a user I want to view other user profiles, so that I can get to know the other users

** Acceptance Criteria**

- [ ] - User profile of a writer can be accessed by clicking the Author's name on a post
- [ ] - Other user's user profiles are not editable

**Tasks**

- [ ] - Profile page must not be editable
- [ ] - Add unit tests
