### ISSUE TITLE
As a User I want to edit my profile, so that I an keep my details up to date

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#49]
EPIC: #39 

As a User I want to edit my profile, so that I an keep my details up to date

** Acceptance Criteria**

- [x] - Editable fields must be editable in the screen
- [x] - Save button must be enabled

**Tasks**

- [x] - Add front-end validation
- [x] - Save button must be active after a change
- [x] - Clicking save must invoke the REST API to save the changes in the DB
