### ISSUE TITLE
As a User I want to create my profile by signing up in the system

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#50]
EPIC: #39 

As a User I want to create my profile by signing up in the system

** Acceptance Criteria**

- [ ] - User profile is crreated with a default profile image
- [ ] - Use profile can be accessed after sigining in once signup is completed

**Tasks**

- [ ] - Design and implement the user signup page
- [ ] - Signup page should accept email and password with a confirmation of the password to create the user
- [ ] - The form should validate the information properly before creating the user

**Comment by chathugaj** [comment]
Duplicate
