### ISSUE TITLE
As a user I can sign in with my username and password, so that I can have access to the content writer features of the blog

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#51]
EPIC: #40 

As a user I can sign in with my username and password, so that I can have access to the content writer features of the blog

** Acceptance Criteria**

- [x] - Sign In page must be accessible to the users from NavBar without logging in
- [x] - Sign In page must contain an email and password fields 
- [x] - Input must be validated and correct error messages should be shown
- [ ] - Sign in page must contain a forgot password link
- [x] - Successful authentication must allow user to write articles and comment other articles

**Tasks**

- [ ] - Design and develop the password page
- [ ] - Design and develop password reset page
- [x] - Implement validation
