### ISSUE TITLE
As a user I want to change my password through a link sent to my email, so that I can change it if I forget

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#52]
EPIC: #40 

As a user I want to change my password through a link sent to my email, so that I can change it if I forget

** Acceptance Criteria**

- [ ] - Forgot password must be available without authentication
- [ ] - Form must accept an email field and validate the value
- [ ] - Upon submitting the form, user should be given a confimation message
- [ ] - User should get an email from the system, when a user completes the flow
- [ ] - User can enter the registered email to the forgot password page
- [ ] - Email link should be valid for a limited time
- [ ] - Clicking valid email link takes the user to the password reset page
- [ ] - The password reset form must get the password and the password conformation from the user
- [ ] - Passwords must be validated

**Tasks**

- [ ] - Design and develop the password page
- [ ] - Design and develop password reset page
- [ ] - Implement validation
- [ ] - Implement security features to prevent unauthorized password resets
- [ ] - Expire password reset links
- [ ] - Send email when the forgot password form is submitted
- [ ] - Unit testing
