### ISSUE TITLE
As an authenticated user only, I can access the article editor, so that I can write articles

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#53]
EPIC: #41 

As an authenticated user only, I can access the article editor, so that I can write articles

** Acceptance Criteria**

- [x] - Users not registered or logged out cannot article editor page is not available
- [x] - If user attempts to go the page user should be taken to the Sign In Page

**Tasks**

- [x] - Implement user authorization based on user's authenticated status
- [x] - Implement redirection to Sign in page if the authorization fails
- [x] - Show the editor if the user is authenticated
