### ISSUE TITLE
As a user I want to create and publish my articles, so that I can share my experience with other fellow travelers

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#55]
EPIC: #42 

As a user I want to create and publish my articles, so that I can share my experience with other fellow travelers

** Acceptance Criteria**

- [x] - Option to add location map, images, title, sub title and content
- [x] - Options to Save, publish, edit, preview a post

**Tasks**

- [x] - Design and develop the post editor page
- [x] - Implement validations
- [x] - Images can be uploaded
- [x] - Preview button shows the preview of the article
- [x] - Ability to delete a post
