### ISSUE TITLE
As a user I want to create and manage my comments on posts

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#56]
EPIC: #42 

As a user I want to create and manage my comments on posts

** Acceptance Criteria**

- [x] - Option to add, edit or delete a comment

**Tasks**

- [x] - Design and develop the comments section
- [x] - Implement validations
- [x] - Show buttons to add, edit and delete
