### ISSUE TITLE
As a user I want to read posts on the website, so that I can enjoy the other traverllers experience

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#57]
EPIC: #43 

As a user I want to read posts on the website, so that I can enjoy the other traverllers experience

** Acceptance Criteria**

- [ ] - Option to view the post on the website
- [ ] - The post should be aligned and displayed in an easy to read manner

**Tasks**

- [ ] - Design and develop the post viewer
- [ ] - Images should be shown if images are available
- [ ] - Map should be shown if the location is available
- [ ] - Show the author name, published date, title, subtitle and content
