### ISSUE TITLE
As a user I want to read comments on a post on the website, so that I can see related experience from other travellers

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#58]
EPIC: #43 

As a user I want to read comments on a post on the website, so that I can see related experience from other travellers

** Acceptance Criteria**

- [x] - Option to view the comments as a list under the post
- [x] - Comments should be aligned with post underneath the post"
- [x] #60

**Tasks**

- [x] - Design and implement the comments list
- [x] - Show the commentors name
- [x] - Design and implement the list of posts
