### ISSUE TITLE
As a user I want to navgate through main pages of the system quickly, so that I can perform tasks I want easily

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#61]
EPIC: #44 

As a user I want to navgate through main pages of the system quickly, so that I can perform tasks I want easily

** Acceptance Criteria**

- [x] - Links to navigate to main pages are available
- [x] - Clicking a link would navigate to.the inteded correct page

**Tasks**

- [x] - Design and implement the Navbar
- [x] - Unit tests
