### ISSUE TITLE
As a user I want to be able to search the artcles with the content, so that I can view articles with certain keywods in the title

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#62]
EPIC: #45 

As a user I want to be able to search the artcles with the content, so that I can view articles with certain keywods in the title

** Acceptance Criteria**

- [x] - A text field to search for the titles is available
- [x] - Posts can be filtered by the destination country
- [x] - Posts can be filtered by the published age
- [x] - List of relevant posts shown in the search results page
- [x] - List should be paginated for better user experience

**Tasks**

- [x] - Design and implement the Search page
- [x] - Implement search by keyword
- [x] - Implement filter by destination country
- [x] - Implement filter by age of the post
- [x] - Implement result pagination
- [x] - Unit tests
