### ISSUE TITLE
As a user I want a contact us page, so that I can report issues or misconduct of other users

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#63]
EPIC: #46 

As a user I want a contact us page, so that I can report issues or misconduct of other users

** Acceptance Criteria**

- [x] - A form to capture the reason, relevant content and a description of the issue
- [x] - Validation on the content

**Tasks**

- [x] - Design and implement the contact us page
- [x] - Implement validation on the form
- [x] - Unit tests
