### ISSUE TITLE
As a developer I want my application deployed in heroku, so that users can start using it

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/travellers-diary#66]
EPIC: #64 

As a developer I want my application deployed in heroku, so that users can start using it

** Acceptance Criteria**

- [x] - Application deployed in heroku
- [x] - It's accessible publicly

**Tasks**
- [x] - Configure application in heroku
- [x] - Make sure the sensitive configuration are secure
- [x] - Make sure the application is accessible and has no issues
